export { Header } from './Header.jsx'
export { MobileFooter } from './MobileFooter.jsx'
export { Products } from './Products.jsx'
export { Footer } from './Footer.jsx'
export { ProductInfo } from './ProductInfo.jsx'
